feat: #WB-1983: add new component Attachment
opendigitaleducation/edifice-ui pull request #13
Opened 2023-09-05 16:18 UTC by Headan

# Description

Ajout d'un nouveau composant `Attachment` + changement du nom de l'icone Attachment en Paperline

Ticket : #WB-1983
https://edifice-community.atlassian.net/browse/WB-1983

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Which Package changed?

Please check the name of the package you changed

- [x] Components
- [ ] Core
- [x] Icons
- [ ] Hooks

## Has the documentation changed?

- [x] Storybook

## Type of change

Please check options that are relevant.

- [x] Chore (PATCH)
- [x] Doc (PATCH)
- [ ] Bug fix (PATCH)
- [ ] New feature (MINOR)
- [ ] Breaking change (MAJOR)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2023-09-05 17:10 UTC, ccreusat requested changes

2023-09-05 17:10 UTC, ccreusat commented on packages/react/src/components/Attachment/Attachment.stories.tsx
> +  title: "Components/AttachmentComponent",
@Headan 

- Renommer la story "Attachment"

2023-09-05 17:10 UTC, ccreusat commented on packages/react/src/components/Attachment/Attachment.stories.tsx
> +  subcomponents: { Button },
@Headan 
Retirer le champ `subcomponent` car ne sert plus à rien avec SB7

2023-09-05 17:10 UTC, ccreusat commented on packages/react/src/components/Attachment/Attachment.tsx
> +      <div ref={ref} className="attachment px-8 py-12" {...restProps}>
@Headan il faut inverser les valeurs de padding, c'est : 

- px-12
- py-8

vu avec simon :)

2023-09-05 17:10 UTC, ccreusat commented on packages/react/src/components/Attachment/Attachment.tsx
> +          <p className="name">{name}</p>
- remplacer le `className="name"` par `className="body"` 

ça prendra bien la font 16px et le line-height 24px

2023-09-05 17:10 UTC, ccreusat commented on packages/react/src/components/Attachment/Attachment.tsx
> +        <div className="options px-2">{options}</div>
vu avec simon, c'est `px-12`

2023-09-06 07:53 UTC, Headan commented on packages/react/src/components/Attachment/Attachment.tsx
> +          <p className="name">{name}</p>
@ccreusat Le problème c'est que j'ai rajouter des propriétés css pour name :/ mais je peux changer son name

2023-09-06 13:47 UTC, ccreusat commented on packages/react/src/components/Attachment/Attachment.tsx
> +          <p className="name">{name}</p>
`body text-truncate`

2023-09-06 14:54 UTC, ccreusat approved these changes

2023-09-06 14:55 UTC, merged

2023-10-25 14:25 UTC, ccreusat commented
:tada: This PR is included in version @edifice-ui/icons-v1.2.0-develop-b2school.1 :tada:

The release is available on:
- [npm package (@develop-b2school dist-tag)](https://www.npmjs.com/package/@edifice-ui/icons/v/1.2.0-develop-b2school.1)
- [GitHub release](https://github.com/opendigitaleducation/edifice-ui/releases/tag/%40edifice-ui/icons-v1.2.0-develop-b2school.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-10-25 14:27 UTC, ccreusat commented
:tada: This PR is included in version @edifice-ui/react-v1.2.0-develop-b2school.1 :tada:

The release is available on:
- [npm package (@develop-b2school dist-tag)](https://www.npmjs.com/package/@edifice-ui/react/v/1.2.0-develop-b2school.1)
- [GitHub release](https://github.com/opendigitaleducation/edifice-ui/releases/tag/%40edifice-ui/react-v1.2.0-develop-b2school.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: