Feat(multimedia): #WB-1976, add MediaLibrary component
opendigitaleducation/edifice-ui pull request #17
Opened 2023-09-13 12:51 UTC by jcbe-ode

# Description

Ajout du composant MediaLibrary et de l'ossature de ses onglets : captation vidéo, captation audio, espace doc...

## Which Package changed?

Please check the name of the package you changed

- [ ] Components
- [ ] Core
- [ ] Icons
- [ ] Hooks
- [X] Multimedia

## Has the documentation changed?

- [X] Storybook

## Type of change

Please check options that are relevant.

- [ ] Chore (PATCH)
- [ ] Doc (PATCH)
- [ ] Bug fix (PATCH)
- [X] New feature (MINOR)
- [ ] Breaking change (MAJOR)

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2023-09-13 16:18 UTC, david-cc commented on packages/react/src/multimedia/MediaLibrary.tsx
> +    if (type) console.log(type);
c'est pour du debug ?

2023-09-13 16:18 UTC, david-cc commented on packages/react/src/multimedia/MediaLibrary.tsx
> +export const useMediaLibrary = (): [MediaLibraryType, (type: any) => void] => {
J'ai pas compris à quoi servait ce hook 😅 j'ai l'impression qu'il n'est pas utilisé

2023-09-13 16:51 UTC, ccreusat requested changes

2023-09-14 14:48 UTC, jcbe-ode commented
Je sors cette PR du mode draft, car les commentaires ont été pris en compte.
Je vous laisse le soin de revoir le tout mais ce composant devra encore évoluer avec le prochaines features à dev (espace doc, upload...)
J'ai attauqé l'espace doc en local.

2023-09-15 07:28 UTC, merged

2023-10-25 14:25 UTC, ccreusat commented
:tada: This PR is included in version @edifice-ui/icons-v1.2.0-develop-b2school.1 :tada:

The release is available on:
- [npm package (@develop-b2school dist-tag)](https://www.npmjs.com/package/@edifice-ui/icons/v/1.2.0-develop-b2school.1)
- [GitHub release](https://github.com/opendigitaleducation/edifice-ui/releases/tag/%40edifice-ui/icons-v1.2.0-develop-b2school.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-10-25 14:27 UTC, ccreusat commented
:tada: This PR is included in version @edifice-ui/react-v1.2.0-develop-b2school.1 :tada:

The release is available on:
- [npm package (@develop-b2school dist-tag)](https://www.npmjs.com/package/@edifice-ui/react/v/1.2.0-develop-b2school.1)
- [GitHub release](https://github.com/opendigitaleducation/edifice-ui/releases/tag/%40edifice-ui/react-v1.2.0-develop-b2school.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: