feat: #WB-2100, add a11y to Toolbar component
opendigitaleducation/edifice-ui pull request #18
Opened 2023-09-13 16:00 UTC by david-cc

# Description

Setup the a11y behaviour for the toolbar component:
- Keyboard Arrow navigation
- Tab/Shift-tab navigation between toolbar and editor content
- Toolbar and button outline on focus

https://edifice-community.atlassian.net/browse/WB-2100

## Which Package changed?

Please check the name of the package you changed

- [X] Components
- [ ] Core
- [ ] Icons
- [ ] Hooks

## Has the documentation changed?

- [ ] Storybook

## Type of change

Please check options that are relevant.

- [ ] Chore (PATCH)
- [ ] Doc (PATCH)
- [ ] Bug fix (PATCH)
- [X] New feature (MINOR)
- [ ] Breaking change (MAJOR)

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

2023-09-13 16:57 UTC, ccreusat requested changes
@david-cc j'ai un comportement bizarre :
- tabulation j'entre dans le composant OK
- je navigue avec les flèches OK
- si je vais sur le dropdown Plus, j'ouvre avec Enter, j'entre dedans avec Tab, mais je peux pas ressortir avec Shift + Tab car ça revient direct sur le premier élément de la toolbar.
- A voir ce qui est possible ?

Et est-ce que, comme le composants Tabs, on est pas censé pouvoir revenir sur le premier élément si on est sur le dernier avec la flèche droite et l'inverse premier élément + flèche gauche va direct sur le dernier ?

2023-09-14 16:05 UTC, david-cc commented
> @david-cc j'ai un comportement bizarre :
> 
> * tabulation j'entre dans le composant OK
> * je navigue avec les flèches OK
> * si je vais sur le dropdown Plus, j'ouvre avec Enter, j'entre dedans avec Tab, mais je peux pas ressortir avec Shift + Tab car ça revient direct sur le premier élément de la toolbar.
> * A voir ce qui est possible ?
> 
> Et est-ce que, comme le composants Tabs, on est pas censé pouvoir revenir sur le premier élément si on est sur le dernier avec la flèche droite et l'inverse premier élément + flèche gauche va direct sur le dernier ?

Ouai le soucis du dropdown je l'ai aussi, c'est pour ça que je disais qu'il fallait sûrement revoir l'accessibilité dans le composant Dropdown, normalement on devrait afficher le dropdown avec la touche Entrée ou Espace puis naviguer dedans avec flèche haut/bas, puis touche Echap pour le refermer.

Pour la navigation dernier élément/premier élément je l'ai implémenté ça devrait marcher mais je crois qu'à cause du dropdown en dernier élément ça marche pas du coup ^^ en fait dès que ya le focus sur le bouton du dropdown ensuite on ne peut plus naviguer avec les flèches. Je sais pas si je peux faire quelque chose par rapport à ça depuis la toolbar.

2023-09-15 07:34 UTC, ccreusat commented
@david-cc 

Ok, bah on verra avec les dropdown revus

2023-09-15 07:40 UTC, ccreusat approved these changes

2023-09-15 07:41 UTC, merged

2023-10-25 14:27 UTC, ccreusat commented
:tada: This PR is included in version @edifice-ui/react-v1.2.0-develop-b2school.1 :tada:

The release is available on:
- [npm package (@develop-b2school dist-tag)](https://www.npmjs.com/package/@edifice-ui/react/v/1.2.0-develop-b2school.1)
- [GitHub release](https://github.com/opendigitaleducation/edifice-ui/releases/tag/%40edifice-ui/react-v1.2.0-develop-b2school.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: