Feat/WB-2093
opendigitaleducation/edifice-ui pull request #24
Opened 2023-09-26 15:48 UTC by Headan

# Description

Ajout d'un nouveau composant CardUpload

Ticket: #WB-2093
Lien: https://edifice-community.atlassian.net/browse/WB-2093

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Which Package changed?

Please check the name of the package you changed

- [x] Components
- [ ] Core
- [ ] Icons
- [ ] Hooks

## Has the documentation changed?

- [x] Storybook

## Type of change

Please check options that are relevant.

- [x] Chore (PATCH)
- [ ] Doc (PATCH)
- [ ] Bug fix (PATCH)
- [ ] New feature (MINOR)
- [ ] Breaking change (MAJOR)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2023-09-27 08:18 UTC, ccreusat requested changes

2023-09-27 08:18 UTC, ccreusat commented on packages/react/src/components/Card/Card.tsx
> +  uploadLoading?: boolean;
@Headan renommer `isLoading` afin d'être générique et s'en servir ailleurs dans le futur mais on a déjà un `isLoading` passé à `Card`. Tu peux te baser sur celui là ?

2023-09-27 08:18 UTC, ccreusat commented on packages/react/src/components/Card/Card.tsx
> +  successUpload?: boolean;
@Headan renommer `status` afin d'être générique et s'en servir ailleurs dans le futur

2023-09-27 08:18 UTC, ccreusat commented on packages/react/src/components/Card/Card.tsx
> +  extensionFile?: string;
@Headan renommer `info` afin d'être générique et s'en servir ailleurs dans le futur

2023-09-27 08:18 UTC, ccreusat commented on packages/react/src/components/Card/Card.tsx
> +        "upload-error": !successUpload,
@Headan `status` : success | warning | error

2023-09-27 08:18 UTC, ccreusat commented on packages/react/src/components/Card/CardUpload.tsx
> +    <div className="card-upload">
@Headan pourquoi tu as besoin de cette classe `card-upload` ? si y'a une surcharge, cette classe devrait être dans le composant principal `Card` sur `className="card ...` comme surcharge `card card-upload`

2023-09-27 08:18 UTC, ccreusat commented on packages/react/src/components/Card/CardUpload.tsx
> +            {uploadLoading ? (
@Headan décomposer ton ternary avec des sous composants dans ce fichier si tu veux pour que ce soit + propre (comme exemple avec Card Resource)

2023-09-27 08:18 UTC, ccreusat commented on packages/react/src/components/Card/CardUpload.tsx
> +          <div className="actions">
@Headan a voir si `actions` peut ne pas être une surcharge de `card-footer` plutôt et que le reste peut être déplacé dans `card-body` (en jouant avec flex , gap, ...)

2023-09-27 09:47 UTC, Headan commented on packages/react/src/components/Card/Card.tsx
> +  uploadLoading?: boolean;
J'ai voulu me baser sur le isLoading existant mais si je me trompe pas le composant a deux chargement différent:
- Le premier charge image + infos de la card
- Le second charge le fichier et pour moi ca ne fait pas partie du même loading 

Mais peut-être que je me trompe

2023-09-29 09:03 UTC, ccreusat commented
⚠️ attention le conflit de CSS @Headan

2023-10-05 09:07 UTC, merged

2023-10-25 14:25 UTC, ccreusat commented
:tada: This PR is included in version @edifice-ui/icons-v1.2.0-develop-b2school.1 :tada:

The release is available on:
- [npm package (@develop-b2school dist-tag)](https://www.npmjs.com/package/@edifice-ui/icons/v/1.2.0-develop-b2school.1)
- [GitHub release](https://github.com/opendigitaleducation/edifice-ui/releases/tag/%40edifice-ui/icons-v1.2.0-develop-b2school.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-10-25 14:27 UTC, ccreusat commented
:tada: This PR is included in version @edifice-ui/react-v1.2.0-develop-b2school.1 :tada:

The release is available on:
- [npm package (@develop-b2school dist-tag)](https://www.npmjs.com/package/@edifice-ui/react/v/1.2.0-develop-b2school.1)
- [GitHub release](https://github.com/opendigitaleducation/edifice-ui/releases/tag/%40edifice-ui/react-v1.2.0-develop-b2school.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: