feat: #WB-2024, add attachment Dropzone + UploadCard in MediaLibrary
opendigitaleducation/edifice-ui pull request #34
Opened 2023-10-18 16:51 UTC by Headan

# Description

Ajout des composants Dropzone + uploadCard dans la  MediaLibrary et faire les connexion API afin de créer les fichiers et les affichés sous forme de Cards. 

Ticket : WB-2024
Lien: https://edifice-community.atlassian.net/browse/WB-2024

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Which Package changed?

Please check the name of the package you changed

- [x] Components
- [ ] Core
- [ ] Icons
- [x] Hooks

## Has the documentation changed?

- [x] Storybook

## Type of change

Please check options that are relevant.

- [x] Chore (PATCH)
- [ ] Doc (PATCH)
- [ ] Bug fix (PATCH)
- [ ] New feature (MINOR)
- [ ] Breaking change (MAJOR)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2023-10-27 07:10 UTC, jcbe-ode approved these changes

2023-10-27 07:44 UTC, ccreusat requested changes

2023-10-27 07:44 UTC, ccreusat commented on packages/react/src/components/Dropzone/Dropzone.stories.tsx
> +    accept: ["mp4", "mp3", "jpg", "png"],
@Headan Sur qu'on peut passer que ces types là ou c'est en exemple ? (cc @jcbe-ode)

2023-10-27 07:44 UTC, ccreusat commented on packages/react/src/components/Dropzone/Dropzone.tsx
> +    <DropzoneContext.Provider value={contextValue}>
@Headan A harmoniser comme les autres composants `contextValue` en `value`

2023-10-27 07:44 UTC, ccreusat commented on packages/react/src/components/Dropzone/Files.tsx
> +  const callHandleSave = async () => {
@Headan A harmoniser d'après la [convention](https://edifice-community.atlassian.net/wiki/spaces/FK/pages/3451879476/Convention#Naming-Events-Handlers) en place
+ un autre [lien](https://javascript.plainenglish.io/handy-naming-conventions-for-event-handler-functions-props-in-react-fc1cbb791364)

2023-10-27 07:44 UTC, ccreusat commented on packages/react/src/components/Dropzone/Files.tsx
> +    callHandleSave();
@Headan si tu utilises qu'une fois `handleOnSave` ;) , tu peux la mettre directement dans ton useEffect avec une async en iife

ex:

```
useEffect(() => {
    (async () => {
      ...
    })();
  }, []);
```

2023-10-27 07:44 UTC, ccreusat commented on packages/react/src/components/Dropzone/Files.tsx
> +  const fileInfo = {
@Headan ça fait beaucoup de cast typescript (as).. A voir si peut mieux faire :D

2023-10-27 07:44 UTC, ccreusat commented on packages/react/src/components/Dropzone/Files.tsx
> +      weight: custumSize(
@Headan `custumSize` ou `customSize` ? :D

2023-10-27 07:44 UTC, ccreusat commented on packages/react/src/hooks/useHandleFiles/useHandleFiles.tsx
> +export default function useHandleFile() {
@Headan le nom du fichier n'a pas le même nom que ton hook (singulier / pluriel)

2023-10-27 07:44 UTC, ccreusat commented on packages/react/src/hooks/useHandleFiles/useHandleFiles.tsx
> +  const [statusUpload, setStatusUpload] = useState<Status | undefined>();
@Headan [status, setStatus] c'est pas suffisant ?

2023-10-27 07:44 UTC, ccreusat commented on packages/react/src/hooks/useHandleFiles/useHandleFiles.tsx
> +  const [statusUpload, setStatusUpload] = useState<Status | undefined>();
ne devrait pas être `undefined` mais `idle` si se passe rien (voir typage Status)

2023-10-27 07:44 UTC, ccreusat commented on packages/react/src/hooks/useHandleFiles/useHandleFiles.tsx
> +  async function handleSave(file: File) {
@Headan convention

2023-10-27 07:44 UTC, ccreusat commented on packages/react/src/hooks/useHandleFiles/useHandleFiles.tsx
> +      const fileUpload = await odeServices.workspace().saveFile(file);
@Headan à voir pour renommer `fileUpload` .. Un `WorkspaceElement` renvoie un `doc` voir le composant Media Library / Workspace fait pas JC. Qu'on s'y retrouve :)

2023-10-27 07:44 UTC, ccreusat commented on packages/react/src/hooks/useHandleFiles/useHandleFiles.tsx
> +      if (fileUpload._id) {
`doc._id`, etc

2023-10-27 07:44 UTC, ccreusat commented on packages/react/src/hooks/useHandleFiles/useHandleFiles.tsx
> +  async function handleDelete(element: WorkspaceElement, index: number) {
@Headan convention

2023-10-27 07:44 UTC, ccreusat commented on packages/react/src/hooks/useHandleFiles/useHandleFiles.tsx
> +      setUploadFiles((oldUploadFiles) =>
`oldUploadFiles`en `prevFiles` > convention

2023-10-27 07:44 UTC, ccreusat commented on packages/react/src/multimedia/MediaLibrary/MediaLibrary.tsx
> +      isEnable: () => (!videoCaptureWorkflow ? true : false),
bizarre cette vérif de code

2023-10-27 07:44 UTC, ccreusat commented on packages/react/src/multimedia/MediaLibrary/MediaLibrary.tsx
> +    onCancel();
onCancel devrait pas être appelé après le await ?
> ça ferme et le await peut ne pas se faire

2023-10-27 07:44 UTC, ccreusat commented on packages/react/src/utils/fileSize.ts
> +export const custumSize = (bytes: number, decimalPoint: number) => {
`customSize`

2023-10-27 12:35 UTC, Headan commented on packages/react/src/components/Dropzone/Files.tsx
> +      weight: custumSize(
custom :p

2023-10-27 12:44 UTC, Headan commented on packages/react/src/multimedia/MediaLibrary/MediaLibrary.tsx
> +    onCancel();
Il se fait mais c'est vrai que c'est mieux a faire dans l'autre sens ^^'

2023-10-27 12:52 UTC, Headan commented on packages/react/src/components/Dropzone/Dropzone.stories.tsx
> +    accept: ["mp4", "mp3", "jpg", "png"],
@ccreusat c'est un exemple pour Storybook mais je vais l'enlever car sur la story ca n'a pas trop de sens

2023-10-30 10:44 UTC, ccreusat requested changes

2023-10-30 10:44 UTC, ccreusat commented on packages/react/src/hooks/useHandleFile/useHandleFile.tsx
dès qu'on embarque du ts-client ou des appels => n'a pas sa place ni dans `components` ni dans `hooks`. 
- à déplacer dans `core` ou si va avec un composant multi, ... dans un sous-dossier `hook`

`hooks` = hook générique sans attache

2023-10-30 10:44 UTC, ccreusat commented on packages/react/src/multimedia/MediaLibrary/innertabs/Upload.tsx
>    const context = useMediaLibraryContext();
même convention que le reste => à destructurer `const { result, setResult, ...} = useMedia..`

2023-10-30 10:44 UTC, ccreusat commented on packages/react/src/multimedia/MediaLibrary/innertabs/Upload.tsx
> +  const handleSuccess = (res: WorkspaceElement[]) => {
on va essayer d'harmoniser le lexique. `res` = `doc` car document de l'espace documentaire

2023-10-30 10:44 UTC, ccreusat commented on packages/react/src/multimedia/UploadCard/UploadCard.tsx
> +              {typeAcceptEdit.find((el) => el === info?.type) && (
`el `à renommer `type` pour être + explicite, non? :)

2023-10-30 10:44 UTC, ccreusat commented on packages/react/src/hooks/useHandleFile/useHandleFile.tsx
> +      if (doc._id) {
y'a besoin du `else` ? il tombe pas dans le catch si le await ne retourne rien. s'il ne retourne rien, y'a pas de doc donc pas de doc._id ?

2023-10-30 10:44 UTC, ccreusat commented on packages/react/src/components/Dropzone/Files.tsx
> +      handleSave();
pas moyen de déplacer directement le code de `handleSave` dans le async du useEffect ? je ne le vois nul part autre

2023-10-31 08:39 UTC, merged

2023-10-31 08:41 UTC, ccreusat commented
:tada: This PR is included in version @edifice-ui/react-v1.2.0-develop-b2school.5 :tada:

The release is available on:
- [npm package (@develop-b2school dist-tag)](https://www.npmjs.com/package/@edifice-ui/react/v/1.2.0-develop-b2school.5)
- [GitHub release](https://github.com/opendigitaleducation/edifice-ui/releases/tag/%40edifice-ui/react-v1.2.0-develop-b2school.5)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: