Feat/wb 1989 Empty screens for the internal linker
opendigitaleducation/edifice-ui pull request #47
Opened 2023-11-06 14:30 UTC by jcbe-ode

# Description

Display the empty-screen illustrations, depending on the current search results.

## Which Package changed?

Please check the name of the package you changed

- [ ] Components
- [ ] Core
- [ ] Icons
- [ ] Hooks
- [X] Multimedia

## Has the documentation changed?

- [ ] Storybook

## Type of change

Please check options that are relevant.

- [ ] Chore (PATCH)
- [ ] Doc (PATCH)
- [ ] Bug fix (PATCH)
- [X] New feature (MINOR)
- [ ] Breaking change (MAJOR)

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

2023-11-07 10:22 UTC, ccreusat requested changes

2023-11-07 10:22 UTC, ccreusat commented on packages/react/src/components/Tabs/TabsList.tsx
> +export interface TabsListProps extends ComponentPropsWithoutRef<"div"> {}
mais directement : `const TabsList = (props: ComponentPropsWithoutRef<"div">) => {`

2023-11-07 10:22 UTC, ccreusat commented on packages/react/src/multimedia/Linker/InternalLinker.tsx
> +    Promise.all(webApps)
@jcbe-ode prioriser async / await un max stp (même remarque sur d'autres bouts de code) et destructurer le retour de Promise.all au max

+ prioriser try / catch / finally

On se fera un atelier ou un point pour parler des méthodos qu'on se synchro tous (async / await, clean code, ...)

```
// exemple
const [conf, applications] = await Promise.all([
      this.getThemeConf(),
      this.getApplicationsList(),
    ]);```

2023-11-07 10:22 UTC, ccreusat commented on packages/react/src/multimedia/Linker/InternalLinker.tsx
> +  useEffect(() => {
@jcbe-ode si possible ordre dans un composant (je crois que j'en parlais dans le workshop react)

1. les imports
2. déclaration du composant
3. les useState regroupés
4. useEffects regroupés au max (quand possible) sauf si dépendant de fonction fléchées vs fonctions normales)
5. les fonctions
6. return JSX

2023-11-07 10:22 UTC, ccreusat commented on packages/react/src/multimedia/Linker/InternalLinker.tsx
> +            imageSrc={`/assets/themes/edifice-bootstrap/images/${theme?.bootstrapVersion}/illu-empty-search.svg`}
@jcbe-ode j'avais fait un hook tout con pour récupérer les chemins des images, icons et fonts, voir => `packages/react/src/core/usePaths/usePaths.ts` (ça peut être just un `util` sinon)

2023-11-07 10:22 UTC, ccreusat commented on packages/react/src/multimedia/MediaLibrary/innertabs/Resource.tsx
> +    context.setResult({
@jcbe-ode même convention que pour les autres composants avec context, on destructure

```
const { setResult }  = useMediaLibraryContext();
```

2023-11-07 10:22 UTC, ccreusat commented on packages/react/src/multimedia/MediaLibrary/innertabs/Resource.tsx
> +        appCode={context.appCode}
@jcbe-ode j'avais pas fait gaffe lors du useMediaLibrary et son context, mais `appCode` est déjà récupérable via `useOdeClient`

```
const { appCode } = useOdeClient()

//
<OdeClientProvider
      params={{
        app: "mindmap",
      }}
    >
...
```

idem pour l'app en cours
```
const {currentApp} = useOdeClient()`

2023-11-07 10:23 UTC, ccreusat commented
⚠️ conflit avec Tablist à mettre à jour

2023-11-07 17:26 UTC, jcbe-ode commented on packages/react/src/components/Tabs/TabsList.tsx
> +export interface TabsListProps extends ComponentPropsWithoutRef<"div"> {}
Exact, c'est corrigé via l'autre PR WB-2215

2023-11-08 15:35 UTC, jcbe-ode commented on packages/react/src/multimedia/Linker/InternalLinker.tsx
> +    Promise.all(webApps)
Pareil, je comprends l'idée d'un code homogène, mais quand il faut faire une IIFE autour, je trouve ça moins lisible :-)

2023-11-08 15:59 UTC, jcbe-ode commented on packages/react/src/multimedia/MediaLibrary/innertabs/Resource.tsx
> +        appCode={context.appCode}
J'en suis bien conscient, malheureusement `useOdeClient` récupére aussi la session de l'utilisateur, rendant le composant dépendant à la présence d'un backend.

Du coup, la MediaLibrary ne fonctionnerait plus dans StoryBook si elle n'avait plus de propriété `appCode`, et qu'à la place, elle aille le chercher dans le contexte du `OdeClientProvider`.

J'ai eu la même problématique dans `InternalLinker`, mais là, pas le choix, la session de l'utilisateur est vraiment nécessaire. Donc InternalLinker ne fonctionne pas dans StoryBook.

2023-11-08 16:53 UTC, merged