Feat/wb 1987: Audio Recorder
opendigitaleducation/edifice-ui pull request #50
Opened 2023-11-13 02:26 UTC by david-cc

# Description

Je n'ai pas réussi à finir le portage du Recorder Audio car l'implémentation est assez complexe.

J'ai d'abord fait un portage en suivant l'API Web Audio, comme pour la vidéo, qui propose une implémentation simple qui génère un Blob final de l'audio entier mais je me suis rendu compte que le backend n'était pas compatible et qu'en cas de gros fichier cela poserait des problèmes de perf car il n'y a pas de limite de temps à la capture audio j'ai l'impression.
Ce portage correspond au premier commit de cette PR : [feat: #WB-1987, AudioRecorder Component with Audio Web API](https://github.com/opendigitaleducation/edifice-ui/commit/4f4d3dc389656353b6b847ba2c29672fea149694).

Ensuite j'ai fait le portage "bête" depuis la version Legacy mais il s'avère que le Processor Audio utilisé (https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/createScriptProcessor) est déprécié, j'ai quand même tenté de l'utiliser pour voir si j'arrivais au bout du portage mais j'ai rencontré des soucis de performance lors de l'enregistrement, l'onglet de captation audio qui freeze :/ sûrement dû à mon implémentation avec React. Cela correspond au 2e commit : [feat: #WB-1987, Audio Recorder Dumb legacy portage](https://github.com/opendigitaleducation/edifice-ui/commit/d7969e4141d531b490f35822b33d0aa4ae3cac9b)

Etant donné ces soucis, j'ai fait le portage vers la nouvelle API de Audio Processor (https://developer.mozilla.org/en-US/docs/Web/API/AudioWorkletProcessor), il y a une PR pour le script de processor sur le dépôt entcore (https://github.com/opendigitaleducation/entcore/pull/410). Avec cette implémentation, on récupère bien le flux audio avec le Processor, puis ensuite il est envoyé à l'audio encoder puis à la Web Socket mais j'ai constaté également des problèmes de perf, la RAM et le CPU qui s'emballe sur l'onglet chrome qui freeze :/ Il faudrait plus de temps pour debugger. 
Au final je n'ai pas pu terminer mais vous pourrez voir l'implémentation dans le 3e commit de cette PR : [feat: #WB-1987, AudioRecorder Component with AudioWorkletNode API](https://github.com/opendigitaleducation/edifice-ui/commit/5b552626d68f561b22ead8de7109d03f798d925d).  

La capture audio est testable en local depuis l'application tiptap-playground, j'ai intégré le composant de Captation Audio dans l'onglet Captation Audio de l'éditeur de texte.

Je pense que ce n'est pas facile de rentrer dans le sujet sans connaissances préalables du Legacy, de l'API Web Audio, du Worker JS et de Web Socket, j'ai essayé de commenter un max sur mon dernier commit...

## Which Package changed?

Please check the name of the package you changed

- [ ] Components
- [ ] Core
- [ ] Icons
- [ ] Hooks

## Has the documentation changed?

- [ ] Storybook

## Type of change

Please check options that are relevant.

- [ ] Chore (PATCH)
- [ ] Doc (PATCH)
- [ ] Bug fix (PATCH)
- [ ] New feature (MINOR)
- [ ] Breaking change (MAJOR)

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2023-11-22 17:00 UTC, Romu-C commented
Dans la continuité des dev de David j’ai poussé un [commit](https://github.com/opendigitaleducation/edifice-ui/commit/afa89c73c58972afbdaed3dd02416b2c5a144886) ajoutant l’envoie au serveur du fichier audio avec l’ajout de la lecture du fichier audio capturé.
Ajout des fonctionnalités iso legacy avec le [commit](https://github.com/opendigitaleducation/edifice-ui/commit/1837e3c0ef5d73259713e04b326127ae7266e131)

2023-11-23 08:59 UTC, ccreusat requested changes

2023-11-23 08:59 UTC, ccreusat commented on packages/react/src/multimedia/AudioRecorder/AudioRecorder.tsx
> +              ? "var(--edifice-danger)"
@Romu-C ne pas utiliser les vars css directement, mais utiliser les classes utilitaires stp
ex: ```bg-success | text-success```

2023-11-23 08:59 UTC, ccreusat commented on packages/react/src/multimedia/AudioRecorder/AudioRecorder.tsx
> +          recordState === "RECORDING" ? { color: "var(--edifice-danger)" } : {}
@Romu-C essayer le plus possible de cleaner avec variables 

```const isRecording = recordState === "RECORDING"

isRecording ? ... : ...
```

merci

2023-11-23 08:59 UTC, ccreusat commented on packages/react/src/multimedia/AudioRecorder/AudioRecorder.tsx
> +        {playState === "IDLE" && (
@Romu-C C'est un assez gros composant. A voir si tu peux l'éclater en plusieurs petits composants (à voir si tu décomposes par "status" => paused, recording, ...

2023-11-23 08:59 UTC, ccreusat commented on packages/react/src/multimedia/MediaLibrary/innertabs/Audio.tsx
>    const context = useMediaLibraryContext();
@Romu-C destructurer le hook stp => même convention partout 👍🏼

2023-11-23 08:59 UTC, ccreusat commented on packages/react/src/multimedia/MediaLibrary/innertabs/Audio.tsx
> +  const handleSuccess = (res: WorkspaceElement) => {
@Romu-C nom explicite => res => resource

2023-11-23 08:59 UTC, ccreusat commented on packages/react/src/multimedia/MediaLibrary/innertabs/Audio.tsx
> +  const handleError = (err: string) => {
@Romu-C err => error (explicit code)

2023-11-23 08:59 UTC, ccreusat commented on packages/react/src/multimedia/MediaLibrary/innertabs/Audio.tsx
> +      onError={handleError}
@Romu-C si props => `onError` = `handleOnError` (faut qu'on uniformise)

2023-11-23 08:59 UTC, ccreusat commented on packages/react/src/multimedia/AudioRecorder/AudioRecorder.tsx
> +  onSuccess: (res: WorkspaceElement) => void;
@Romu-C idem pour le typage => res => resource 

c'était bon sur error ici :)

2023-11-23 09:44 UTC, Romu-C commented on packages/react/src/multimedia/AudioRecorder/AudioRecorder.tsx
> +              ? "var(--edifice-danger)"
Ah j'arrivai pas à trouver ces classes :(

2023-11-23 10:28 UTC, jcbe-ode commented on public/infra/public/js/audio-recorder-processor.js
Les 2 scripts ici sont nécessaires pour storybook ?

2023-11-23 10:28 UTC, jcbe-ode commented on packages/react/src/multimedia/AudioRecorder/useAudioRecorder.tsx
> +    const audioContext = new AudioContext({ sampleRate: DEFAULT_SAMPLE_RATE });
La fréquence d'échantillonnage par défaut est ici de 48000 Hz,  mais dans audioEncoder.js, par défaut, c'est 44100 Hz (qualité CD).
Je me demande laquelle des 2 valeurs est la bonne, probablement 44100.

2023-11-23 10:37 UTC, jcbe-ode commented on packages/react/src/multimedia/MediaLibrary/innertabs/Audio.tsx
> +      onError={handleError}
Hummm es-tu sûr de la syntaxe handle**On**Error ?
https://edifice-community.atlassian.net/wiki/spaces/FK/pages/3451879476/Convention#Naming-Events-Handlers

2023-11-23 13:00 UTC, Romu-C commented on public/infra/public/js/audio-recorder-processor.js
Oui audio-recorder-processor est la pour pourvoir récupérer le flux audio et le manipuler
et audio-encorder et la pour encore les flux audio reçu.

2023-11-24 10:43 UTC, merged