[EDIFICE] Feat/wb 1984 Editeur d'image
opendigitaleducation/edifice-ui pull request #76
Opened 2023-12-07 17:51 UTC by nabil-mansouri

# Description

Ce commit embarque l'éditeur d'image et tout les effets pixi qui sont lié à la modale de l'éditeur
Il embarque également des hooks facilitant:
- la création/maj dans workspace
- la manipulation des images selectionné dans tiptap 

## Which Package changed?

Please check the name of the package you changed

- [ ] Components
- [X ] Core
- [ ] Icons
- [] Hooks

## Has the documentation changed?

- [ ] Storybook

## Type of change

Please check options that are relevant.

- [ ] Chore (PATCH)
- [ ] Doc (PATCH)
- [ ] Bug fix (PATCH)
- [X] New feature (MINOR)
- [ ] Breaking change (MAJOR)

# Checklist:

- [ ] My code follows the style guidelines of this project
- [X ] I have performed a self-review of my code
- [X ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X ] My changes generate no new warnings

2023-12-07 19:17 UTC, ccreusat commented on packages/react/src/multimedia/ImageEditor/components/ImageEditor.tsx
> +const ImageEditor: React.FC<ImageEditorProps> = ({
@nabil-mansouri pas de React.FC stp

2023-12-07 19:18 UTC, ccreusat commented on packages/react/src/multimedia/ImageEditor/components/ImageEditorToolbar.tsx
> +const ImageEditorToolbar: React.FC<ImageEditorToolbarProps> = ({ handle }) => {
pas de React.FC

2023-12-07 19:19 UTC, ccreusat commented on packages/react/src/multimedia/ImageEditor/hooks/useHistoryTool.tsx
y'a besoin de l'extension `tsx`?

2023-12-07 19:20 UTC, ccreusat commented on packages/react/src/multimedia/ImageEditor/hooks/useImageEditor.tsx
idem, y'a pas besoin que ce soit une extension `.tsx` ?

2023-12-07 19:21 UTC, ccreusat commented on packages/react/src/multimedia/ImageEditor/hooks/useImageEffects.ts
> +    if (application === undefined) return;
tu peux peut être simplifier les if ?
```
if (!application)
```

2023-12-12 07:03 UTC, jcbe-ode requested changes

2023-12-12 07:03 UTC, jcbe-ode commented on packages/react/src/multimedia/ImageEditor/hooks/useImageEditor.tsx
> +    setApplication,
setApplication, j'ai du mal à voir comment ça s'utilise.
Ne peut-on pas complètement encapsuler pixi, de manière à ce que les applis utilisant nos hooks soient totalement ignorantes de son existence et ne créent aucun lien de dépendance dessus ? Mettre un exemple en story ?

2023-12-12 09:04 UTC, nabil-mansouri commented on packages/react/src/multimedia/ImageEditor/hooks/useImageEditor.tsx
> +    setApplication,
il permet de stocker le contexte PIXI dans un state car le composant pixi react crée ce context onMount j'ai besoin de le conserver et eventuellement de le mettre à jour si il change
après pour totalement découpler il faudrait que je crée une interface IApplication ou IContext mais ca serait une interface qui aurait la même que celle de pixi donc au final pas tant découpler car les opérations dépendent fortement de la lib

2023-12-12 09:06 UTC, nabil-mansouri commented on packages/react/src/multimedia/ImageEditor/hooks/useImageEditor.tsx
> +    if (application === undefined) return undefined;
updateImage impose que l'objet soit undefined (en réalité toutes les fonctions dans le dossier effects)
il n'y a que dans le contexte react que application est potentiellement undefined car le mount de pixi react n'a pas encore eu lieu. c'est pourquoi j'ai mis les check undefined dans le hook plutôt

2023-12-12 09:06 UTC, nabil-mansouri commented on packages/react/src/multimedia/ImageEditor/utils/debounceAggregate.ts
> +export function debounceAggregate<INPUT, OUTPUT>(
en fonction des retours de recette je vais supprimer une des deux fonctions j'ai préféré garder les 2 dans un premier temps et j'attend de voir ce que christophe dira sur l'effet de floutage

2023-12-13 07:39 UTC, merged