Feat: #WB-2012 Video Embed
opendigitaleducation/edifice-ui pull request #77
Opened 2023-12-08 14:11 UTC by Romu-C

# Description

Add video embed feature in MediaLyb modal

## Which Package changed?

Please check the name of the package you changed

- [x] Components
- [ ] Core
- [x] Icons
- [ ] Hooks

## Has the documentation changed?

- [x] Storybook

## Type of change

Please check options that are relevant.

- [ ] Chore (PATCH)
- [ ] Doc (PATCH)
- [ ] Bug fix (PATCH)
- [x] New feature (MINOR)
- [ ] Breaking change (MAJOR)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2023-12-08 16:39 UTC, ccreusat requested changes

2023-12-08 16:39 UTC, ccreusat commented on packages/icons/assets/image-not-found.svg
@Romu-C à retirer et à utiliser l'image prévue pour le contenu non trouvé > https://github.com/opendigitaleducation/edifice-bootstrap/blob/41149fcf513e8a1d01499f31f7d6f2e371096490/assets/images/emptyscreen/illu-error.svg

2023-12-08 16:39 UTC, ccreusat commented on packages/icons/src/ImageNotFound.tsx
@Romu-C à retirer

2023-12-08 16:39 UTC, ccreusat commented on packages/react/src/multimedia/VideoEmbed/VideoEmbed.tsx
> +      {debounceChangeUrl && embedder && (
@Romu-C quand tu as une tonne de condition, tu peux cleaner et faire des fonction de render
Ex: https://github.com/opendigitaleducation/edifice-ui/blob/27574175423c57ebb24bdffb4f3244428067f3d0/packages/react/src/components/Combobox/Combobox.tsx > `renderContent`

2023-12-12 07:26 UTC, jcbe-ode requested changes

2023-12-12 07:26 UTC, jcbe-ode commented on packages/react/src/multimedia/VideoEmbed/VideoEmbed.tsx
> +      <FormControl id="iframeContent">
Mettre un id, c'est obligatoire pour les formulaires ?
Si non, autant l'enlever (en supposant qu'aucune règle CSS ne l'utilise pour styler le formulaire)
Si oui, mieux vaut utiliser [useId](https://react.dev/reference/react/useId)
Car en mettant une constante, on ne pourra jamais utiliser 2x <VideoEmbed> dans la même page (règle d'accessibilité).

2023-12-12 07:26 UTC, jcbe-ode commented on packages/react/src/multimedia/VideoEmbed/VideoEmbed.tsx
> +    if (url?.length) {
```suggestion
    onSuccess( url?.length ? url : undefined );
```

2023-12-12 16:42 UTC, merged