Feat/wb 2391
opendigitaleducation/edifice-ui pull request #84
Opened 2024-01-02 16:36 UTC by jcbe-ode

# Description

Following the refactor of tiptap playground, the new components and hooks are moved to a new edifice-ui package : editor.
This new lib will be used by the playground, and every other resource-producing apps.

Contains also a fix of useHelp, and a little refactor of OdeClientContext, splitted in 2.
`useOdeClient` hook remains the same, but it should be splitted in 2 also (this would require refactoring explorer...)
Anyway, i've got a problem with react providers :rofl: 

## Which Package changed?

Please check the name of the package you changed

- [ ] Components
- [ ] Core
- [ ] Icons
- [ ] Hooks

## Has the documentation changed?

- [ ] Storybook

## Type of change

Please check options that are relevant.

- [ ] Chore (PATCH)
- [ ] Doc (PATCH)
- [ ] Bug fix (PATCH)
- [ ] New feature (MINOR)
- [ ] Breaking change (MAJOR)

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2024-01-03 08:14 UTC, ccreusat requested changes
@jcbe-ode pourquoi appeler le package `editor`plutôt que `tiptap` quand la glue avec est assez forte ? :D

2024-01-03 08:14 UTC, ccreusat commented on packages/editor/src/styles/table.scss
@jcbe-ode n'a rien à faire ici, il doit être externalisé

2024-01-03 08:14 UTC, ccreusat commented on packages/react/src/core/OdeClientProvider/AppProvider.tsx
@jcbe-ode pas de refacto des providers, on en reparle plus tard stp, merci

2024-01-03 08:30 UTC, jcbe-ode commented
> @jcbe-ode pourquoi appeler le package `editor`plutôt que `tiptap` quand la glue avec est assez forte ? :D

Parce que le nom tiptap pourrait être déposé, un jour. On ne devrait pas faire référence à des "marques" dans nos libs...

2024-01-03 10:48 UTC, Romu-C commented on packages/editor/src/styles/table.scss
> +      border: 2px solid #ced4da;
Il faudrait utiliser des variables pour les couleurs

2024-01-03 11:18 UTC, jcbe-ode commented on packages/editor/src/styles/table.scss
J'ai pu mettre _table.css_ dans edifice-bootstrap facilement.
Par contre, y mettre aussi `katex` me semblait overkill...

Pour l'instant, il y a un soucis avec `katex` si on veut le placer dans _edifice-ui/editor_ : le CSS n'est pas injectable dans le JS final; à la place de générer du code javascript (comme dans le playground, voir _public/index-hash.js_), cela tente d'importer littéralement le fichier;
`import '../../node_modules/.pnpm/katex@0.16.8/node_modules/katex/dist/katex.min.css.js';`

Des solutions peuvent exister, à creuser : voir https://github.com/vitejs/vite/issues/1579 (sauf erreur de ma part)

2024-01-04 14:47 UTC, jcbe-ode commented on packages/editor/src/styles/table.scss
Corrigé par un commit de hacker pro :smile:  https://github.com/opendigitaleducation/edifice-ui/pull/84/commits/0d253706cefe9e467e974bda51050d368fef5880

2024-01-05 08:18 UTC, merged